version: '3'
services: 
  api:
    image: davidbohl/user-service-api
    restart: always
    build: .
    command: npm run dev
    ports: 
      - "5000:3000"
    links: 
      - mongo
    depends_on: 
      - mongo 
    volumes: 
      - .:/home/node/app
    env_file: environment_api.env
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27217:27017"
    volumes:
      - /userservice/data:/data/db
    env_file: environment_mongo.env